Add clean code changes
AngelinaTsunik/aircompany pull request #1
Opened 2021-11-10 17:52 UTC by AngelinaTsunik

2021-11-12 10:38 UTC, rimus requested changes

2021-11-12 10:38 UTC, rimus commented on JS/test/airport.spec.js
> +     assert.equal(hasTransportTypeInMilitaryPlane, true);
`assert.isTrue()`?

2021-11-12 10:38 UTC, rimus commented on JS/test/airport.spec.js
> +          assert.fail("Test failed!");
Poor description.

2021-11-12 10:38 UTC, rimus commented on JS/test/airport.spec.js
> +            if (experimentalPlane.ClassificationLevel === ClassificationLevel.unclassified) {
`experimentalPlane.classificationLevel`?

2021-11-12 10:38 UTC, rimus commented on JS/models/classificationLevel.js
>  };
It is better to use following pattern:
```
const someEnumeration = {
  VALUE_ONE: ...,
  VALUE_TWO: ...,
  VALUE_THREE: ...,
  VALUE_FOUR: ...,
}
```

2021-11-12 10:38 UTC, rimus commented on JS/models/experimentalType.js
> +};
It is better to use following pattern:
```
const someEnumeration = {
  VALUE_ONE: ...,
  VALUE_TWO: ...,
  VALUE_THREE: ...,
  VALUE_FOUR: ...,
}
```

2021-11-12 10:38 UTC, rimus commented on JS/models/militaryType.js
>  };
It is better to use following pattern:
```
const someEnumeration = {
  VALUE_ONE: ...,
  VALUE_TWO: ...,
  VALUE_THREE: ...,
  VALUE_FOUR: ...,
}
```

2021-11-12 12:48 UTC, AngelinaTsunik commented on JS/test/airport.spec.js
> +     assert.equal(hasTransportTypeInMilitaryPlane, true);
fixed

2021-11-12 12:48 UTC, AngelinaTsunik commented on JS/test/airport.spec.js
> +          assert.fail("Test failed!");
fixed

2021-11-12 12:48 UTC, AngelinaTsunik commented on JS/test/airport.spec.js
> +            if (experimentalPlane.ClassificationLevel === ClassificationLevel.unclassified) {
fixed

2021-11-12 12:48 UTC, AngelinaTsunik commented on JS/models/classificationLevel.js
>  };
fixed

2021-11-12 12:48 UTC, AngelinaTsunik commented on JS/models/experimentalType.js
> +};
fixed

2021-11-12 12:48 UTC, AngelinaTsunik commented on JS/models/militaryType.js
>  };
fixed

2021-11-15 14:31 UTC, rimus approved these changes
Looks good.

2021-11-16 07:13 UTC, merged